"""empty message

Revision ID: b1ef337c173a
Revises: 
Create Date: 2024-01-31 16:18:44.387447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ef337c173a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oscillators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('osc_type', sa.String(length=20), nullable=False),
    sa.Column('gain', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('attack', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('decay', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sustain', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('release', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oscillators')
    op.drop_table('favorites')
    op.drop_table('patches')
    op.drop_table('users')
    # ### end Alembic commands ###
