# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster
WORKDIR /docker-app
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
EXPOSE 5000
RUN chmod u+x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]