services:  
  postgres:   
    restart: always    
    image: postgres   
    environment:      
      - POSTGRES_USER=postgres    
      - POSTGRES_PASSWORD=postgres   
      - POSTGRES_DB=new-synthia
    volumes:      
      - ./postgres-data/postgres:/var/lib/postgresql/data    
    ports:      
      - "5432:5432"
      
  app:    
    restart: always    
    build: .    
    ports:      
      - 5000:5000    
    volumes:      
      - .:/app
