"""empty message

Revision ID: 41424dd413bd
Revises: 8fee633916b2
Create Date: 2023-09-20 15:23:12.545513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41424dd413bd'
down_revision = '8fee633916b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_patch_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'patch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_patch_association')
    op.drop_table('favorite')
    # ### end Alembic commands ###
