"""empty message

Revision ID: 95085899e132
Revises: 67e89c33ff37
Create Date: 2023-09-07 16:25:09.863665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95085899e132'
down_revision = '67e89c33ff37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_patch_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'patch_id')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('favorite_patch_association')
    # ### end Alembic commands ###
