"""empty message

Revision ID: 9b726d95884d
Revises: 3aff23b43ec8
Create Date: 2023-09-20 17:02:51.920115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b726d95884d'
down_revision = '3aff23b43ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_patch_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_patch_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.id'], name='favorite_patch_association_patch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_patch_association_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'patch_id', name='favorite_patch_association_pkey')
    )
    # ### end Alembic commands ###
